#!/usr/bin/env ansible-playbook
- name: Do something
  hosts: all
  gather_facts: yes

  tasks:
    - name: Include OS specific tasks
      ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
